-- Generated by nwg-displays on 2026-09-04 at 17:42:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1920x0",
    scale = 1,
    mirror = "eDP-1",
    bitdepth = 10
})
