-- Generated by nwg-displays on 2026-09-16 at 15:42:13. Do not edit manually.

hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
