-- Generated by nwg-displays on 2026-09-04 at 17:58:44. Do not edit manually.

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
