# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e1e2e8"

# Title color for boxes
theme[title]="#a3c9fe"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bcc7db"

# Background color of selected item in processes box
theme[selected_bg]="#a3c9fe"

# Foreground color of selected item in processes box
theme[selected_fg]="#00315c"

# Color of inactive/disabled text
theme[inactive_fg]="#c3c6cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d9bde3"

# Cpu box outline color
theme[cpu_box]="#8d9199"

# Memory/disks box outline color
theme[mem_box]="#8d9199"

# Net up/down box outline color
theme[net_box]="#8d9199"

# Processes box outline color
theme[proc_box]="#8d9199"

# Box divider line and small boxes line color
theme[div_line]="#43474e"

# Temperature graph colors
theme[temp_start]="#bcc7db"
theme[temp_mid]="#a3c9fe"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#bcc7db"
theme[cpu_mid]="#a3c9fe"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bcc7db"
theme[free_mid]=""
theme[free_end]="#3c4758"

# Mem/Disk cached meter
theme[cached_start]="#d9bde3"
theme[cached_mid]=""
theme[cached_end]="#543f5e"

# Mem/Disk available meter
theme[available_start]="#a3c9fe"
theme[available_mid]=""
theme[available_end]="#1e4876"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#bcc7db"
theme[download_mid]="#a3c9fe"
theme[download_end]="#d9bde3"

# Upload graph colors
theme[upload_start]="#bcc7db"
theme[upload_mid]="#a3c9fe"
theme[upload_end]="#d9bde3"