# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e4e1e9"

# Title color for boxes
theme[title]="#bec2ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c5c4dd"

# Background color of selected item in processes box
theme[selected_bg]="#bec2ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#272b60"

# Color of inactive/disabled text
theme[inactive_fg]="#c7c5d0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e8b9d5"

# Cpu box outline color
theme[cpu_box]="#91909a"

# Memory/disks box outline color
theme[mem_box]="#91909a"

# Net up/down box outline color
theme[net_box]="#91909a"

# Processes box outline color
theme[proc_box]="#91909a"

# Box divider line and small boxes line color
theme[div_line]="#46464f"

# Temperature graph colors
theme[temp_start]="#c5c4dd"
theme[temp_mid]="#bec2ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c5c4dd"
theme[cpu_mid]="#bec2ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c5c4dd"
theme[free_mid]=""
theme[free_end]="#444559"

# Mem/Disk cached meter
theme[cached_start]="#e8b9d5"
theme[cached_mid]=""
theme[cached_end]="#5e3c52"

# Mem/Disk available meter
theme[available_start]="#bec2ff"
theme[available_mid]=""
theme[available_end]="#3d4278"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c5c4dd"
theme[download_mid]="#bec2ff"
theme[download_end]="#e8b9d5"

# Upload graph colors
theme[upload_start]="#c5c4dd"
theme[upload_mid]="#bec2ff"
theme[upload_end]="#e8b9d5"